name: "RenPy Install"
author: 'PaxlavaGames'
description: "Download RenPy SDK"
inputs:
  version:
    description: "SDK version"
    required: false
    default: "8.2.0"
  download_web:
    description: "Download Web Extension"
    required: false
    default: "no"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.download_web }}
branding:
  color: 'purple'
  icon: 'arrow-down'
