name: Install RenPy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        renpy-version: [ "8.1.3", "8.2.0" ]
    steps:
    - uses: actions/checkout@v3
    - name: Install RenPy ${{ matrix.renpy-version }}
      uses: PaxlavaGames/renpy-install@main
      with:
        version: ${{ matrix.renpy-version }}
        download_web: true
    - name: Check folders
      run: |
        ls
        ls renpy
