name: Install RenPy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install RenPy
      uses: PaxlavaGames/renpy-install@main
      with:
        version: "8.1.3"
    - name: Check folders
      run: |
        ls